apiVersion: apps/v1
kind: Deployment
metadata:
  name: exosphere-state-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exosphere-state-manager
  template:
    metadata:
      labels:
        app: exosphere-state-manager
    spec:
      containers:
        - name: exosphere-state-manager
          image: ghcr.io/exospherehost/exosphere-state-manager:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: exosphere-state-manager-secrets
          env:
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exosphere-redis-auth
                  key: redis-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10