# traefik-values.yaml
deployment:
  podAnnotations:
    prometheus.io/scrape: "true"

additionalArguments:
  - "--entrypoints.web.address=:8081"
  - "--entrypoints.websecure.address=:8443"

ports:
  web:
    port: 8081
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false        # turn on later if you want the UI

certificatesResolvers:
  letsencrypt:
    acme:
      email: "nivedit@exosphere.host"
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web   # solve the challenge on :80
