name: Ruff check for python code

on:
    push: 
        branches: 
            - main
        paths: 
            - 'api-server/**'
            - 'state-manager/**'
    pull_request:
        branches:
            - main
        paths:
            - 'api-server/**'
            - 'state-manager/**'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pages: write

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Ruff Check
              uses: astral-sh/ruff-action@v3
              with:
                src: './api-server'
            - name: Ruff Check
              uses: astral-sh/ruff-action@v3
              with:
                src: './state-manager'
